/**
 * Centralized user-facing text for easy translation.
 * Flat structure — many strings shared across pages.
 * Use: import S from './strings' then S.username, S.save, etc.
 * For templates: format(S.editLabelTemplate, { label: 'Hair Types' })
 */
export function format(template, vars = {}) {
  if (typeof template !== 'string') return '';
  return template.replace(/\{(\w+)\}/g, (_, key) => vars[key] ?? `{${key}}`);
}

const strings = {
  search: 'Search',
  cancel: 'Cancel',
  save: 'Save',
  update: 'Update',
  edit: 'Edit',
  add: 'Add',
  back: 'Back',
  done: 'Done',
  delete: 'Delete',
  remove: 'Remove',
  select: 'Select…',
  loading: 'Loading…',
  saving: 'Saving…',
  next: 'Next',
  confirmDeleteTitle: 'Are you sure?',
  confirmDeleteDefault: 'This action cannot be undone.',
  deleteButton: 'Delete',

  username: 'Username',
  password: 'Password',
  email: 'Email',
  firstName: 'First Name',
  lastName: 'Last Name',
  confirmPassword: 'Confirm Password',

  login: 'Login',
  logout: 'Logout',
  loginLoading: 'Logging in…',
  loginError: 'Login failed',
  noAccount: "Don't Have An Account?",
  signUpLink: 'Sign Up',
  loginIssues: 'Having issues logging in?',
  resetPasswordLink: 'Reset Your Password',

  createAccount: 'Create Account',
  signUp: 'Sign Up',
  signUpLoading: 'Creating account…',
  signUpError: 'Signup failed',
  passwordsMismatch: 'Passwords do not match',
  hasAccount: 'Already have an account?',
  loginLink: 'Login',

  resetPassword: 'Reset Password',
  resetPasswordFor: 'Reset password for',
  changeYourPassword: 'Change your password',
  newPassword: 'New Password',
  sendResetLink: 'Send Reset Link',
  sending: 'Sending…',
  requestFailed: 'Request failed',
  checkYourEmail: 'Check your email',
  resetEmailSent: 'If an account exists for that email, a reset link has been sent.',
  backToLogin: 'Back to Login',

  home: 'Home',
  surgeries: 'Surgeries',
  patients: 'Patients',
  team: 'Team',
  settings: 'Settings',
  accounts: 'Accounts',
  globalDefaults: 'Global Defaults',

  goodMorning: 'Good Morning',
  goodAfternoon: 'Good Afternoon',
  goodEvening: 'Good Evening',
  activeSurgeries: 'Active Surgeries',
  upcoming: 'Upcoming',
  past: 'Past',
  patient: 'Patient',
  extractionStarted: 'Extraction Started',
  placingStarted: 'Placing Started',
  grafts: 'Grafts',
  date: 'Date',
  goal: 'Goal',
  actions: 'Actions',
  dashboard: 'Dashboard',
  report: 'Report',
  newSurgery: 'New Surgery',
  emptyActiveSurgeries: 'No Active Surgeries',
  emptyUpcomingSurgeries: 'No Upcoming Surgeries',
  emptyPastSurgeries: 'No Past Surgeries',

  surgeriesTitle: 'Surgeries',
  noSurgeriesFound: 'No Surgeries Found',
  surgeryDeleteConfirm: 'Delete this surgery? All associated graft data will be permanently removed.',

  startSurgery: 'Start Surgery',
  starting: 'Starting…',
  finishSurgery: 'Finish Surgery',
  surgery: 'Surgery',
  graftGoal: 'Graft Goal',
  addTechnicians: 'Add technicians (optional)',
  editTechnicians: 'Edit Technicians',
  editDoctor: 'Edit Doctor',
  selectTechnicians: 'Select technicians',
  noTechnicians: 'No technicians in this account',
  name: 'Name',
  hair: 'Hair',
  caliber: 'Caliber',
  extraction: 'Extraction',
  placement: 'Placement',
  started: 'Started',
  statusCompleted: 'COMPLETED',
  statusInProgress: 'IN PROGRESS',
  graftCount: 'GRAFT COUNT',
  singleHairCount: 'SINGLE HAIR COUNT',
  total: 'TOTAL',
  startTimer: 'Start',
  stopTimer: 'Stop',
  completeExtraction: 'Complete Extraction',
  restartTimer: 'Restart Timer',
  resumeTimer: 'Resume',
  completePlacement: 'Complete Placement',
  statusNotStarted: 'NOT STARTED',
  techDashSummary: 'Summary',
  techDashActivity: 'Activity',
  techDashWaitForStartTitle: 'Surgery not started',
  techDashWaitForStartBody:
    'Your doctor must start this surgery from the dashboard before you can log grafts.',
  techEditButtonsSelectedHelp: 'Selected (visible on your buttons)',
  techEditButtonsAvailableHelp: 'Available (click to add)',
  techEditButtonsNoneSelected: 'None selected',
  techEditButtonsAllSelected: 'All buttons selected',
  techEditButtonsConfigureHint:
    'No graft buttons configured. Ask your account owner to add them in Settings.',
  graftButtonsHelper: 'Add graft types in Settings → Application Settings → Graft Buttons',
  activityLog: 'Activity Log',
  activityLogHelper: 'Rolling log of button clicks',
  noActivity: 'No activity yet',
  noActivitySecondary: 'Clicks will appear here',
  correctGraftType: 'Correct graft type',
  bulkAdd: 'Bulk Add',
  bulkAddTitle: 'Bulk add grafts',
  bulkAddCountLabel: 'How many',
  bulkAddHint: 'Creates one activity row with this quantity — you can correct or remove it later.',
  bulkAddInvalidCount: 'Enter a whole number of at least 1.',
  bulkAddMaxCount: 'You can add at most {max} at once.',
  bulkAddSelectType: 'Select a graft type.',
  bulkAddFailed: 'Could not add grafts. Try again or a smaller count.',
  activityLogBulkPrimary: '{count}× {label}',
  bulkAddClear: 'Clear',
  graftType: 'Graft type',
  viewReport: 'View Report',
  exportPdf: 'Export PDF',

  reportTitle: 'HAIR TRANSPLANT SURGERY REPORT',
  patientInfo: 'Patient Information',
  surgeryDetails: 'Surgery Details',
  surgeryTiming: 'Surgery Timing',
  extractionTiming: 'Extraction Timing',
  placingTiming: 'Placing Timing',
  graftCountingSummary: 'Graft Counting Summary by Technician',
  technicianPerformanceSummary: 'Technician Performance Summary',
  graftSummaryByType: 'Graft Summary by Type',
  patientId: 'Patient ID',
  dateOfBirth: 'Date of Birth',
  hairType: 'Hair Type',
  hairColor: 'Hair Color',
  hairCaliber: 'Hair Caliber',
  skinColor: 'Skin Color',
  physician: 'Physician',
  surgeryGoal: 'Surgery Goal',
  fueDevice: 'FUE Device',
  tipStyle: 'Tip Style',
  tipSize: 'Tip Size',
  holdingSolution: 'Holding Solution',
  placingDevice: 'Placing Device',
  startTime: 'Start Time',
  finishTime: 'Finish Time',
  totalSxTime: 'Total Sx Time',
  totalTime: 'Total Time',
  phone: 'Phone',
  totalGrafts: 'TOTAL GRAFTS',
  totalHairs: 'TOTAL HAIRS',
  singleGrafts: 'SINGLE GRAFTS',
  transRateHair: 'TRANS. RATE (HAIR)',
  transRateGrafts: 'TRANS. RATE (GRAFTS)',
  hairCount: 'Hair Count',
  potHair: 'Pot Hair',
  reportGeneratedOn: 'Report generated on',
  poweredBy: 'Powered By',
  surgAssist: 'SURG ASSIST',
  byCaliforniaHairSurgeon: 'BY CALIFORNIA HAIR SURGEON',
  todo: 'todo',
  todoPerTechnician: 'todo — per-technician graft counts not yet in data model',
  todoPerTechnicianMetrics: 'todo — per-technician metrics not yet in data model',

  selectPatient: 'Select Patient',
  or: 'or',
  newPatient: '+ New Patient',
  newPatientTitle: 'New Patient',
  patientInitials: 'Patient Initials',
  patientDob: 'Patient DOB',
  surgeon: 'Surgeon',
  selectSurgeon: 'Select doctor…',
  surgicalGoal: 'Surgical Goal',
  fueDeviceUsed: 'FUE Device Used',
  fueTipStyle: 'FUE Tip Style',
  fueTipSize: 'FUE Tip Size',
  placingDeviceUsed: 'Placing Device Used',
  initialsRequired: 'Patient initials are required',
  selectOrCreatePatient: 'Please select a patient or create a new one',
  createSurgeryFailed: 'Failed to create surgery',

  patientsTitle: 'Patients',
  noPatientsFound: 'No Patients Found',
  number: '#',
  initials: 'Initials',
  dob: 'DOB',
  added: 'Added',
  initialsHelper: 'e.g. J.D. — no full name stored',
  dobPlaceholder: 'MM/DD/YYYY',
  editPatient: 'Edit Patient',
  createPatientFailed: 'Failed to create patient',
  updatePatientFailed: 'Failed to update patient',
  removePatientConfirm: 'Remove patient {initials}? Their surgery history will be preserved.',
  surgicalHistory: 'Surgical History',
  noSurgeriesOnRecord: 'No surgeries on record.',
  status: 'Status',
  view: 'View',
  backToPatients: 'Back to Patients',
  patientTitle: 'Patient {initials}',
  profile: 'Profile',
  identity: 'Identity',
  hairAndSkin: 'Hair & Skin',
  totalSurgeries: 'Total surgeries',
  recordCreated: 'Record created',
  active: 'Active',
  surgeryHistoryLabel: 'Surgery History',
  goalPercent: 'Goal %',

  teamTitle: 'Team',
  addMember: 'Add Member',
  noTeamMembersFound: 'No Team Members Found',
  noDoctorsFound: 'No Doctors Found',
  noTechniciansFound: 'No Technicians Found',
  role: 'Role',
  roleOwner: 'Owner',
  lastActive: 'Last Active',
  technician: 'Technician',
  doctor: 'Doctor',
  addTeamMember: 'Add Team Member',
  editMember: 'Edit Member',
  emailOptional: 'Email (optional)',
  usernamePasswordRequired: 'Username and password are required',
  addUserFailed: 'Failed to add user',
  usernameRequired: 'Username is required',
  updateUserFailed: 'Failed to update user',
  removeFromTeamConfirm: 'Remove {name} from the team?',
  tabsAll: 'All',
  tabsDoctors: 'Doctors',
  tabsTechnicians: 'Technicians',

  techniciansTitle: 'Technicians',
  addTechnician: 'Add Technician',
  editTechnician: 'Edit Technician',
  addTechnicianFailed: 'Failed to add technician',
  updateTechnicianFailed: 'Failed to update technician',

  settingsTitle: 'Settings',
  settingsAdminUseClinicsList:
    'Open a clinic from the Clinics list to view and edit its settings. Global defaults are under Admin → Global Defaults.',
  personalTitle: 'Personal',
  personalDescription: 'Your name, contact info, and login security.',
  companyTitle: 'Clinic',
  companyDescription: 'Practice information shown throughout the application.',
  applicationTitle: 'Application Settings',
  applicationDescription: 'Dropdown options available when creating patients and surgeries.',
  emailHelper: 'Used for password resets',
  resetButton: 'Reset',
  linkSent: 'Link sent',
  practiceName: 'Practice Name',
  website: 'Website',
  address: 'Address',
  practiceLogoAlt: 'Practice logo',
  clinicLogo: 'Clinic Logo',
  logoFileTypes: 'PNG, JPG up to 5MB',
  uploadLogo: 'Upload Logo',
  updateLogo: 'Update Logo',
  uploadingLogo: 'Uploading…',
  logoTooLarge: 'Image must be 5MB or smaller.',
  logoUploadFailed: 'Could not upload logo. Try a smaller file or check your connection.',
  logoTapToRetry: 'Tap to choose another file.',
  logoNoLogoYet: 'No logo yet',
  graftButtons: 'Graft Buttons',
  graftButtonDefault: 'Default',
  editButtons: 'Edit Buttons',
  intactPlaceholder: 'Intact',
  totalPlaceholder: 'Total',
  hairTypes: 'Hair Types',
  hairColors: 'Hair Colors',
  hairCalibers: 'Hair Calibers',
  skinColors: 'Skin Colors',
  surgeons: 'Surgeons',
  doctors: 'Doctors',
  fueDevices: 'FUE Devices',
  fueTipStyles: 'FUE Tip Styles',
  fueTipSizes: 'FUE Tip Sizes',
  holdingSolutions: 'Holding Solutions',
  placingDevices: 'Placing Devices',
  editLabelTemplate: 'Edit {label}',
  addLabelTemplate: 'Add {label}',
  addFailed: 'Failed to add',
  deleteFailed: 'Failed to delete',
  reorderFailed: 'Failed to reorder',

  statusActive: 'ACTIVE',
  saveStatusSaving: 'Saving…',
  saveStatusSaved: 'Saved',
  saveStatusError: 'Save failed',

  accountsTitle: 'Accounts',
  defaultsTitle: 'Application Defaults',
  defaultsDescription: 'Default values for new accounts. Each account can fully customize after creation.',
  companies: 'Clinics',
  companiesTitle: 'Clinics',
  openDashboard: 'Open Dashboard',
  viewDashboard: 'View Dashboard',
  techniciansCount: 'Technicians',
  doctorsCount: 'Doctors',
  lastActivity: 'Last Activity',
  adminViewingTemplate: 'Admin viewing {name}',
  noCompanies: 'No clinics yet',
  createCompany: 'Create Clinic',
  createCompanyCreating: 'Creating…',
  createCompanyFailed: 'Failed to create clinic',
  createCompanyPracticePlaceholder: 'e.g. California Hair Surgeon',
  createCompanyOwnerSection: 'Account owner (will sign in with username/password)',
  createCompanyCredentialsTitle: 'Credentials for new owner',
  createCompanyCredentialsHelp: 'Share these credentials with the account owner. They can change their password after logging in.',
  createCompanySuccess: 'Clinic and account owner created successfully.',
  copy: 'Copy',
  deleteCompanyConfirm: 'Delete this clinic? All associated data (users, surgeries, patients) will be permanently removed.',

  adminSurgeries: 'Surgeries',
  adminSurgeriesTitle: 'All Surgeries',
  filterByCompany: 'Filter by clinic',
  allCompanies: 'All clinics',
  exportCsv: 'Export CSV',
  company: 'Clinic',

  pickSurgery: 'Pick a Surgery',
  counting: 'Counting',

  appTestTitle: 'API test harness',
  appTestIntro:
    'Runs API calls one after another and records duration in milliseconds. Purge requires the server to be started with ENABLE_APP_TEST_HARNESS=1 (deletes the entire test account). Does not use your normal browser session.',
  appTestRun: 'Run full sequence',
  appTestRunning: 'Running…',
  appTestStep: 'Step',
  appTestMs: 'ms',
  appTestTotal: 'Total',
  appTestStatus: 'Result',
  appTestOk: 'OK',
  appTestFail: 'Failed',
  appTestHarnessDisabled: 'Purge skipped or failed: enable ENABLE_APP_TEST_HARNESS=1 on the server.',

  appTestStep_signup: '1. Signup (create account + seed)',
  appTestStep_login: '2. Login',
  appTestStep_createDoctor: '3. Create doctor user',
  appTestStep_createTechnician: '4. Create technician user',
  appTestStep_createPatient: '5. Create patient',
  appTestStep_createSurgery: '6. Create surgery',
  appTestStep_loadSurgeries: '7. GET surgeries (list)',
  appTestStep_loadPatients: '8. GET patients (list)',
  appTestStep_loadHome: '9. GET surgeries (home-style refresh)',
  appTestStep_loadSurgeryDetail: '10. GET surgery by id',
  appTestStep_loadOptions: '11. GET settings options',
  appTestStep_startSurgery: '12. PATCH surgery → active (start)',
  appTestStep_loginTech: '13. Login as technician',
  appTestStep_loadSurgeriesTech: '14. GET surgeries as technician',
  appTestStep_loadSurgeryTech: '15. GET surgery as technician',
  appTestStep_activities100: '16. POST 100 extraction activities (sequential)',
  appTestStep_logoutTech: '17. Clear session (technician)',
  appTestStep_loginDoctor: '18. Login as doctor',
  appTestStep_loadSurgeriesDr: '19. GET surgeries as doctor',
  appTestStep_loadSurgeryDr: '20. GET surgery as doctor',
  appTestStep_loadActivities: '21. GET surgery activities',
  appTestStep_loginOwnerPurge: '22. Login as account owner (before purge)',
  appTestStep_purge: '23. Purge test account (server)',
};

export default strings;
